
token = "token"

drop_channels = [
  778414238061428766
]
present_log = 778410033926897685
cooldown_time = 30  # seconds for cooldown

drop_chance = 0.1  # chance for drop per message as float (0.1 is 10%, etc)


admin_users = [
  248245568004947969,
  240973228632178689
]

# a list of guild IDs to pull static emotes from
emoji_sources = [
  272885620769161216,
  356869031870988309,
  356876866952364032,
  356876897403011072,
  396144014128054275,
  494946907181809667
]
gift_colors = [ 
  'red',
  'blue',
  'green',
  'purple',
  'yellow',
  'orange',
  'mint',
  'pink',
  'magenta',
  'black',
  'white',
  'gray',
  'brown'
]
try_again = [
  "You found another label on the side of the present.",
  "Let's try again.",
  "There is another label on the bottom of the present."
]
embed_url = 'https://cdn.discordapp.com/attachments/542422265254641674/778763462759022632/googlegiftmintavatarmini.png'

gift_strings = [
  "ğŸ {0} just sent a ğŸˆ Football to {1}. John Madden is proud of you.",
  "ğŸ {0} just sent a ğŸ“¹ï¸ GIF to {1}. Its expiration date was supposed to be years ago.",
  "ğŸ {0} just sent a ğŸª† Matryoshka doll to {1}. There's a lot of dolls in one single package!",
  "ğŸ {0} just sent a ğŸ® Video Game to {1}. Unfortunately, a sequel has been released right now.",
  "ğŸ {0} just sent a ğŸ›· Sled to {1}. It's completely useless without snow!",
  "ğŸ {0} just sent a â­ Star to {1}. {1} absorbed the star somehow.",
  "ğŸ {0} just sent a ğŸ± Magic 8 Ball to {1}. It's good for everything except predictions.",
  "ğŸ {0} just sent a ğŸ Checkered Flag to {1}. {1} wins a race thanks to it.",
  "ğŸ {0} just sent a ğŸ³ï¸ White Flag to {1}, surrendering themselves to {1}.",
  "ğŸ {0} just sent a ğŸª Cookie to {1}. {1} promptly attempts to click on it.",
  "ğŸ {0} just sent a ğŸ± Cat to {1}. The cat climbs up a furniture, ignoring everyone.",
  "ğŸ {0} just sent a ğŸ¶ Dog to {1}. The dog aims for the couch, thrashing it completely.",
  "ğŸ {0} just sent a ğŸ€ Bow to {1}. A perfect accessory for a doll or a pet.",
  "ğŸ {0} just sent a <:bloblamp:580597913600655370> Lamp to {1}. Wait a minute, there's not supposed to be a blob there!",
  "ğŸ {0} just sent a <:b4nzyblob:396521772905922562> b1nzy blob to {1}. The power of the ban hammer scares {1} away.",
  "ğŸ {0} just sent a ğŸï¸ Toy car to {1}. The toy car managed to give hours of entertainment successfully.",
  "ğŸ {0} just sent a ğŸ† Trophy to {1}. This is when you celebrate your moment of victory, if you had one!"
]
[reward_roles]
# Roles given to users once they reach a certain gift sent and gift receive threshold
# The role is given only if both thresholds are met
roles_list = [
  {nbSent = 70, nbReceived = 30, roleId = 778778734500380722}
]

[database]
# The keyword arguments that get passed into database connectors.
# If you're using the docker-compose, you do not need to change this.
host = "db"
port = 5432
user = "postgres"
password = ""
database = ""
max_size = 20
timeout = 60
