
token = "token"

drop_channels = [
  778414238061428766
]
present_log = 778410033926897685
cooldown_time = 30  # seconds for cooldown

drop_chance = 0.1  # chance for drop per message as float (0.1 is 10%, etc)



admin_users = [
  248245568004947969,
  240973228632178689
]

# a list of guild IDs to pull static emotes from
emoji_sources = [
  272885620769161216,
  356869031870988309,
  356876866952364032,
  356876897403011072,
  396144014128054275,
  494946907181809667
]
hints = [
  'Stuck? Type ".list" to show a list of participating names.',
  'Stuck? Type ".giveup" to give up on this present and get a new one next time.'
]
embed_url = 'https://cdn.discordapp.com/attachments/542422265254641674/778763462759022632/googlegiftmintavatarmini.png'

gift_emojis = [
  '<:googlegiftyellow2:779906229119615017>',
  '<:googlegiftyellow:779906229094711296>',
  '<:googlegiftwhite:779906228956299264>',
  '<:googlegiftred2:779906229052243978>',
  '<:googlegiftred:779906229237579786>',
  '<:googlegiftpurple:779906229082390539>',
  '<:googlegiftpink2:779906229060763658>',
  '<:googlegiftpink:779906228977401866>',
  '<:googlegiftowo:779906229187117116>',
  '<:googlegiftorange:779906228913831957>',
  '<:googlegiftmint:779906228943978516>',
  '<:googlegiftindigo:779906228964294666>',
  '<:googlegiftgreen:779906228931133440>',
  '<:googlegiftgray:779906228838334485>',
  '<:googlegiftbrown:779906228830076959>',
  '<:googlegiftblue:779906228507377735>',
  '<:googlegiftblack:779906228238680095>'
]

gift_icons = [
  'https://cdn.discordapp.com/emojis/779865590189391893.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590096855092.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590357688371.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590516940811.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590260826174.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590566879252.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590810148915.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590483517482.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590495576104.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590549577748.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590504357948.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590517071902.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590310895647.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590584049674.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590516678656.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590487187496.png?v=1',
  'https://cdn.discordapp.com/emojis/779865590504488970.png?v=1'
]

gift_strings = [
  "ğŸ {0} just sent a ğŸˆ Football to {1}. John Madden is proud of you.",
  "ğŸ {0} just sent a ğŸ“¹ï¸ GIF to {1}. Its expiration date was supposed to be years ago.",
  "ğŸ {0} just sent a ğŸª† Matryoshka doll to {1}. There's a lot of dolls in one single package!",
  "ğŸ {0} just sent a ğŸ® Video Game to {1}. Unfortunately, a sequel has been released right now.",
  "ğŸ {0} just sent a ğŸ›· Sled to {1}. It's completely useless without snow!",
  "ğŸ {0} just sent a â­ Star to {1}. {1} absorbed the star somehow.",
  "ğŸ {0} just sent a ğŸ± Magic 8 Ball to {1}. It's good for everything except predictions.",
  "ğŸ {0} just sent a ğŸ Checkered Flag to {1}. {1} wins a race thanks to it.",
  "ğŸ {0} just sent a ğŸ³ï¸ White Flag to {1}, surrendering themselves to {1}.",
  "ğŸ {0} just sent a ğŸª Cookie to {1}. {1} promptly attempts to click on it.",
  "ğŸ {0} just sent a ğŸ± Cat to {1}. The cat climbs up a furniture, ignoring everyone.",
  "ğŸ {0} just sent a ğŸ¶ Dog to {1}. The dog aims for the couch, thrashing it completely.",
  "ğŸ {0} just sent a ğŸ€ Bow to {1}. A perfect accessory for a doll or a pet.",
  "ğŸ {0} just sent a <:bloblamp:580597913600655370> Lamp to {1}. Wait a minute, there's not supposed to be a blob there!",
  "ğŸ {0} just sent a <:b4nzyblob:396521772905922562> b1nzy blob to {1}. The power of the ban hammer scares {1} away.",
  "ğŸ {0} just sent a ğŸï¸ Toy car to {1}. The toy car managed to give hours of entertainment successfully.",
  "ğŸ {0} just sent a ğŸ† Trophy to {1}. This is when you celebrate your moment of victory, if you had one!",
  "ğŸ {0} just sent a ğŸ° Piece of Cake to {1}. Sadly, you've been lied to, it's not real.",
  "ğŸ {0} just sent a ğŸ”‹ Battery to {1}. It's so good, that it isn't included with toys.",
  "ğŸ {0} just sent a ğŸ¦  Microbe to {1}. {0} and {1} have been quarantined immediately.",
  "ğŸ {0} just sent a ğŸ“· Camera to {1}. It's completely irrelevant nowadays.",
  "ğŸ {0} just sent a ğŸ“± Smartphone to {1}. Do you folks not have phones?!",
  "ğŸ {0} just sent a ğŸ“• Book to {1}. The perfect source of information, but a terrible one for rainbows.",
  "ğŸ {0} just sent a âš¾ Baseball to {1}. {1} catches it successfully!",
  "ğŸ {0} just sent a ğŸ’¿ CD to {1}. You already downloaded its content before.",
  "ğŸ {0} just sent a ğŸ“€ DVD to {1}. There's nothing that can read its contents!",
  "ğŸ {0} just sent a ğŸ’» Laptop to {1}. It's portable and powerful.",
  "ğŸ {0} just sent ğŸ‡§ğŸ‡· Brazil to {1}. {1} is going there, and so are you.",
  "ğŸ {0} just sent a ğŸªƒ Boomerang to {1}. They're certainly gonna get it back, though.",
  "ğŸ {0} just sent an ğŸ¥š Egg to {1}. Can I offer you a nice egg in this trying time?",
  "ğŸ {0} just sent a ğŸ¦€ Crab to {1}. If you bring it close to your ear, you can hear what it sounds like to be attacked by a crab.",
  "ğŸ {0} just sent a ğŸ–¨ï¸ Printer to {1}. It's cheaper than just buying new cartridges.",
  "ğŸ {0} just sent a ğŸ•µï¸ Spy to {1}. Please don't tell them until the investigation has concluded.",
  "ğŸ {0} just sent âœ‚ï¸ Scissors to {1}. They need another pair to open the wrapper though.",
  "ğŸ {0} just sent a ğŸ¥ Drum to {1}. I believe {0} hates {1}'s parents.",
  "ğŸ {0} just sent a ğŸ’ Bouquet to {1}. {1} blushes intensively.",
  "ğŸ {0} just sent ğŸ¥« Dog Food to {1}. It might actually be for their dog, but who knows.",
  "ğŸ {0} just sent a ğŸ›µ Scooter to {1}. By using it, {1} can change position.",
  "ğŸ {0} just sent a ğŸ—¨ï¸ Text Balloon to {1}. This isn't a comic at all!",
  "ğŸ {0} just sent ğŸ’° Money to {1}. Gifts are cool, but we all like cold hard cash too.",
  "ğŸ {0} just sent a ğŸ¹ Bow to {1}. {1} doesn't know archery and expected something for their doll or pet.",
  "ğŸ {0} just sent a ğŸƒ Pumpkin to {1}. {0} still thinks that it's October.",
  "ğŸ {0} just sent an ğŸ¦‰ Owl to {1}. An awesome friend, especially during sleepless nights.",
  "ğŸ {0} just sent a ğŸ›‘ Stop Sign to {1}. It has 8 fantastic sides and 8 awesome angles.",
  "ğŸ {0} just sent ğŸ§» Toilet Paper to {1}. A very expensive gift, take care of it.",
  "ğŸ {0} just sent ğŸ§‚ Salt to {1}. In case League of Legends doesn't bring enough.",
  "ğŸ {0} just sent a ğŸ€ Rat to {1}. It preys at night and stalks at night.",
  "ğŸ {0} just sent a ğŸŒ­ Hotdog to {1}. Still better than dog food I guess?",
  "ğŸ {0} just sent a ğŸ¸ Guitar to {1}. After doing a sick guitar solo, {1} smashes it on the ground.",
  "ğŸ {0} just sent a ğŸ¤– Bot to {1}. Let's hope it doesn't use JavaScript.",
  "ğŸ {0} just sent ğŸ‘€ Eyes to {1}. Having a second pair of eyes on your work is always useful!",
  "ğŸ {0} just sent a ğŸ¦† Duck to {1}. It's not as good as rubber ducks.",
  "ğŸ {0} just sent a ğŸ¦· Tooth to {1}. You don't want to know where it comes from.",
  "ğŸ {0} just sent a ğŸª¨ Rock to {1}. {1} counterattacks with paper!",
  "ğŸ {0} just sent a ğŸ¥– Baguette to {1}. Ah oui, this is a very good cadeau.",
  "ğŸ {0} just sent a ğŸ› Bug to {1}. As if they didn't write enough bad code already.",
  "ğŸ {0} just sent a ğŸ‘‘ Crown to {1}. Everyone bow to {1} XIV the Great now!",
  "ğŸ {0} just sent a ğŸ´â€â˜ ï¸ Pirate Flag to {1}. Both decide to become pirates.",
  "ğŸ {0} just sent an ğŸ§¯ Extinguisher to {1}. If it ever catches fire itself, just put it away with the rest of the fire.",
  "ğŸ {0} just sent a ğŸ§“ Boomer to {1}. People say \"ok boomer\" but never ask \"Are you ok, boomer?\"",
  "ğŸ {0} just sent an â° Alarm Clock to {1}. The alarm rings, {1} was dreaming the whole time."
]
[reward_roles]
# Roles given to users once they reach a certain coin threshold
roles_list = [
  {nbSent = 70, nbReceived = 30, roleId = 778778734500380722}
]
[database]
# The keyword arguments that get passed into database connectors.
# If you're using the docker-compose, you do not need to change this.
host = "db"
port = 5432
user = "postgres"
password = ""
database = ""
max_size = 20
timeout = 60
